# Generated by Django 5.2.9 on 2025-12-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='status',
            field=models.CharField(choices=[('ok', 'успешно'), ('error', 'не успешно')], default='ok', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('created', 'создана'), ('started', 'запущена'), ('finally', 'завершена')], default='created', max_length=50, verbose_name='Статус'),
        ),
    ]
